version: "3.7"

services:
  api:
    container_name: gita-api
    image: bhagavadgita/bhagavad-gita-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8081:8081
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    depends_on:
      - database
    env_file:
      - .env
    restart: on-failure:5

  database:
    container_name: gita-db
    image: postgres:12-alpine
    volumes:
      - ./db_data:/var/lib/postgresql
    env_file:
      - .env
    restart: on-failure:5

  redis-server:
    container_name: gita-redis
    image: redis:6.0-alpine
    restart: on-failure:5

  celery-worker:
    container_name: gita-celery-worker
    image: bhagavadgita/bhagavad-gita-api
    command: celery -A bhagavad_gita_api.cronjobs worker -l INFO
    depends_on:
      - api
      - redis-server
    env_file:
      - .env
    restart: on-failure:5

  celery-beat-worker:
    container_name: gita-celery-beat-worker
    image: bhagavadgita/bhagavad-gita-api
    command: celery -A bhagavad_gita_api.cronjobs beat -l INFO
    depends_on:
      - api
      - redis-server
    env_file:
      - .env
    restart: on-failure:5
